### ISSUE TITLE
ensure warning about "this looks like a Jekyll site" is properly targeted

### ISSUE THREAD

**Issue by fool** [netlify/netlify-setup-heuristics#4]
Apparently the github-pages gem includes jekyll under the hood, so we should warn more appropriately about that when it is present rather than jekyll.

(ref https://app.intercom.io/a/apps/q245f50x/inbox/a/search/conversations/6486406473 )

**Comment by fool** [comment]
David has some thoughts on how to do this :)

**Comment by calavera** [comment]
won't fix
